# Generated by Django 5.2.17 on 2026-09-08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("attempts", "0001_learning_foundation"),
        ("questions", "0002_question_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewCycle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "origin_kind",
                    models.CharField(
                        choices=[("INITIAL_ERROR", "Erro inicial")],
                        default="INITIAL_ERROR",
                        max_length=24,
                    ),
                ),
                ("policy_code", models.CharField(default="REV-FIXA-1.0", max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Ativo"),
                            ("COMPLETED", "Concluído"),
                            ("SUSPENDED", "Suspenso"),
                        ],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("suspension_reason", models.CharField(blank=True, max_length=1000, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "origin_attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="originated_review_cycle",
                        to="attempts.attempt",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cycles",
                        to="questions.question",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="review_cycles",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_reviewcycle",
                "indexes": [
                    models.Index(
                        fields=["workspace", "question", "state"],
                        name="cycle_ws_q_state_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("state", "ACTIVE")),
                        fields=("question",),
                        name="cycle_active_question_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("origin_kind__in", ["INITIAL_ERROR"])),
                        name="cycle_origin_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("policy_code", "REV-FIXA-1.0")),
                        name="cycle_policy_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("state__in", ["ACTIVE", "COMPLETED", "SUSPENDED"])),
                        name="cycle_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lock_version__gte", 1)),
                        name="cycle_lock_positive",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("state", "ACTIVE"),
                                ("suspended_at__isnull", True),
                                ("suspension_reason__isnull", True),
                            )
                            | models.Q(
                                ("completed_at__isnull", False),
                                ("state", "COMPLETED"),
                                ("suspended_at__isnull", True),
                                ("suspension_reason__isnull", True),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("state", "SUSPENDED"),
                                ("suspended_at__isnull", False),
                                ("suspension_reason__isnull", False),
                            )
                        ),
                        name="cycle_state_dates_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("suspension_reason__isnull", True))
                        | ~models.Q(("suspension_reason", "")),
                        name="cycle_suspend_reason_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence_number", models.PositiveIntegerField()),
                (
                    "stage_code",
                    models.CharField(
                        choices=[("D1", "D1"), ("D7", "D7"), ("D14", "D14"), ("D30", "D30")],
                        max_length=8,
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendente"),
                            ("COMPLETED", "Concluída"),
                            ("SUSPENDED", "Suspensa"),
                            ("CANCELLED", "Cancelada"),
                        ],
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                ("first_due_date", models.DateField()),
                ("current_due_date", models.DateField()),
                ("transition_code", models.CharField(max_length=64)),
                ("policy_code", models.CharField(default="REV-FIXA-1.0", max_length=64)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("suspended_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="questions.question",
                    ),
                ),
                (
                    "review_cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="reviews.reviewcycle",
                    ),
                ),
                (
                    "scheduled_from_attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scheduled_reviews",
                        to="attempts.attempt",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviews",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "reviews_review",
                "indexes": [
                    models.Index(
                        fields=["workspace", "state", "current_due_date", "created_at"],
                        name="review_ws_state_due_idx",
                    ),
                    models.Index(
                        fields=["workspace", "question", "state"],
                        name="review_ws_q_state_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("review_cycle", "sequence_number"),
                        name="review_cycle_sequence_uq",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("state", "PENDING")),
                        fields=("review_cycle",),
                        name="review_cycle_pending_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence_number__gte", 1)),
                        name="review_sequence_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("stage_code__in", ["D1", "D7", "D14", "D30"])),
                        name="review_stage_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("state__in", ["PENDING", "COMPLETED", "SUSPENDED", "CANCELLED"])
                        ),
                        name="review_state_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("policy_code", "REV-FIXA-1.0")),
                        name="review_policy_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("lock_version__gte", 1)),
                        name="review_lock_positive",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("completed_at__isnull", True),
                                ("state", "PENDING"),
                                ("suspended_at__isnull", True),
                            )
                            | models.Q(
                                ("completed_at__isnull", False),
                                ("state", "COMPLETED"),
                                ("suspended_at__isnull", True),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("state", "SUSPENDED"),
                                ("suspended_at__isnull", False),
                            )
                            | models.Q(
                                ("completed_at__isnull", True),
                                ("state", "CANCELLED"),
                                ("suspended_at__isnull", True),
                            )
                        ),
                        name="review_state_dates_valid",
                    ),
                    models.CheckConstraint(
                        condition=~models.Q(("transition_code", "")),
                        name="review_transition_not_empty",
                    ),
                ],
            },
        ),
    ]
