# Generated by Django 5.2.17 on 2026-09-10

import django.db.models.deletion
from django.db import migrations, models


def backfill_origin_revisions(apps, schema_editor):
    """Trace existing error cycles without inventing any new learning facts."""
    ReviewCycle = apps.get_model("reviews", "ReviewCycle")
    for cycle in ReviewCycle.objects.filter(origin_question_revision__isnull=True).iterator():
        cycle.origin_question_revision_id = cycle.origin_attempt.question_revision_id
        cycle.save(update_fields=["origin_question_revision"])


class Migration(migrations.Migration):
    dependencies = [
        ("attempts", "0002_review_receipt_constraints"),
        ("reviews", "0001_learning_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewcycle",
            name="origin_question_revision",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="originated_review_cycles",
                to="questions.questionrevision",
            ),
        ),
        migrations.RunPython(backfill_origin_revisions, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="reviewcycle",
            name="origin_attempt",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="originated_review_cycle",
                to="attempts.attempt",
            ),
        ),
        migrations.AlterField(
            model_name="reviewcycle",
            name="origin_kind",
            field=models.CharField(
                choices=[
                    ("INITIAL_ERROR", "Erro inicial"),
                    ("QUESTION_ACTIVATION", "Ativacao da questao"),
                ],
                default="INITIAL_ERROR",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="reviewcycle",
            name="origin_question_revision",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="originated_review_cycles",
                to="questions.questionrevision",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="scheduled_from_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="scheduled_reviews",
                to="attempts.attempt",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="reviewcycle",
            name="cycle_origin_kind_valid",
        ),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin_kind__in", ["INITIAL_ERROR", "QUESTION_ACTIVATION"])),
                name="cycle_origin_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("origin_attempt__isnull", False), ("origin_kind", "INITIAL_ERROR")
                )
                | models.Q(
                    ("origin_attempt__isnull", True), ("origin_kind", "QUESTION_ACTIVATION")
                ),
                name="cycle_origin_attempt_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=models.Q(("scheduled_from_attempt__isnull", False))
                | models.Q(
                    ("sequence_number", 1),
                    ("stage_code", "D1"),
                    ("transition_code", "QUESTION_ACTIVATION_D1"),
                ),
                name="review_activation_anchor_valid",
            ),
        ),
    ]
