"""S2A manual-cycle origin and immutable schedule history.

Purpose: add MANUAL to the existing closed origin constraints and create the
additive ReviewScheduleChange table. V0.4.4 cycles/reviews need no backfill and
retain their origin, first/current due dates and scheduling policy. New history
fields are non-null because only new confirmed changes create rows. Reversal is
safe before manual cycles or schedule changes exist; after functional use it
would erase origin/history and therefore restore is recommended. Risk: high
because operational dates must remain atomically explainable.
"""

# Generated by Django 5.2.17 on 2026-09-20 15:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("attempts", "0002_review_receipt_constraints"),
        ("questions", "0002_question_catalog"),
        ("reviews", "0002_activation_review_cycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReviewScheduleChange",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("previous_due_date", models.DateField()),
                ("new_due_date", models.DateField()),
                ("timezone_name", models.CharField(max_length=64)),
                ("reason_code", models.CharField(max_length=64)),
                ("correlation_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "reviews_reviewschedulechange",
            },
        ),
        migrations.RemoveConstraint(
            model_name="reviewcycle",
            name="cycle_origin_kind_valid",
        ),
        migrations.RemoveConstraint(
            model_name="reviewcycle",
            name="cycle_origin_attempt_valid",
        ),
        migrations.AlterField(
            model_name="reviewcycle",
            name="origin_kind",
            field=models.CharField(
                choices=[
                    ("INITIAL_ERROR", "Erro inicial"),
                    ("QUESTION_ACTIVATION", "Ativacao da questao"),
                    ("MANUAL", "Inclusão manual"),
                ],
                default="INITIAL_ERROR",
                max_length=24,
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("origin_kind__in", ["INITIAL_ERROR", "QUESTION_ACTIVATION", "MANUAL"])
                ),
                name="cycle_origin_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("origin_attempt__isnull", False), ("origin_kind", "INITIAL_ERROR")),
                    models.Q(
                        ("origin_attempt__isnull", True), ("origin_kind", "QUESTION_ACTIVATION")
                    ),
                    models.Q(("origin_attempt__isnull", False), ("origin_kind", "MANUAL")),
                    _connector="OR",
                ),
                name="cycle_origin_attempt_valid",
            ),
        ),
        migrations.AddField(
            model_name="reviewschedulechange",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="schedule_changes",
                to="reviews.review",
            ),
        ),
        migrations.AddField(
            model_name="reviewschedulechange",
            name="workspace",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="review_schedule_changes",
                to="accounts.workspace",
            ),
        ),
        migrations.AddIndex(
            model_name="reviewschedulechange",
            index=models.Index(
                fields=["workspace", "review", "created_at"], name="schedule_ws_review_time_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewschedulechange",
            constraint=models.CheckConstraint(
                condition=models.Q(("reason_code", ""), _negated=True),
                name="schedule_reason_not_empty",
            ),
        ),
    ]
