# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("reviews", "0003_reviewschedulechange_and_more")]

    operations = [
        migrations.RemoveConstraint(
            model_name="review",
            name="review_activation_anchor_valid",
        ),
        migrations.RemoveConstraint(
            model_name="reviewcycle",
            name="cycle_state_valid",
        ),
        migrations.RemoveConstraint(
            model_name="reviewcycle",
            name="cycle_state_dates_valid",
        ),
        migrations.RemoveConstraint(
            model_name="reviewcycle",
            name="cycle_origin_kind_valid",
        ),
        migrations.RemoveConstraint(
            model_name="reviewcycle",
            name="cycle_origin_attempt_valid",
        ),
        migrations.AddField(
            model_name="reviewcycle",
            name="superseded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewcycle",
            name="origin_kind",
            field=models.CharField(
                choices=[
                    ("INITIAL_ERROR", "Erro inicial"),
                    ("QUESTION_ACTIVATION", "Ativacao da questao"),
                    ("MANUAL", "Inclusão manual"),
                    ("ATTEMPT_CORRECTION", "Correção de tentativa"),
                ],
                default="INITIAL_ERROR",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="reviewcycle",
            name="state",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Ativo"),
                    ("COMPLETED", "Concluído"),
                    ("SUSPENDED", "Suspenso"),
                    ("SUPERSEDED", "Substituído por reconstrução"),
                ],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="review",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(scheduled_from_attempt__isnull=False)
                    | models.Q(
                        sequence_number=1,
                        stage_code="D1",
                        transition_code__in=(
                            "QUESTION_ACTIVATION_D1",
                            "CORRECTION_RETRY_VOIDED",
                        ),
                    )
                ),
                name="review_activation_anchor_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    origin_kind__in=[
                        "INITIAL_ERROR",
                        "QUESTION_ACTIVATION",
                        "MANUAL",
                        "ATTEMPT_CORRECTION",
                    ]
                ),
                name="cycle_origin_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(origin_kind="INITIAL_ERROR", origin_attempt__isnull=False)
                    | models.Q(
                        origin_kind="QUESTION_ACTIVATION",
                        origin_attempt__isnull=True,
                    )
                    | models.Q(origin_kind="MANUAL", origin_attempt__isnull=False)
                    | models.Q(origin_kind="ATTEMPT_CORRECTION")
                ),
                name="cycle_origin_attempt_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(state__in=["ACTIVE", "COMPLETED", "SUSPENDED", "SUPERSEDED"]),
                name="cycle_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        state="ACTIVE",
                        completed_at__isnull=True,
                        suspended_at__isnull=True,
                        superseded_at__isnull=True,
                        suspension_reason__isnull=True,
                    )
                    | models.Q(
                        state="COMPLETED",
                        completed_at__isnull=False,
                        suspended_at__isnull=True,
                        superseded_at__isnull=True,
                        suspension_reason__isnull=True,
                    )
                    | models.Q(
                        state="SUSPENDED",
                        completed_at__isnull=True,
                        suspended_at__isnull=False,
                        superseded_at__isnull=True,
                        suspension_reason__isnull=False,
                    )
                    | models.Q(
                        state="SUPERSEDED",
                        suspended_at__isnull=True,
                        superseded_at__isnull=False,
                        suspension_reason__isnull=True,
                    )
                ),
                name="cycle_state_dates_valid",
            ),
        ),
    ]
