# Generated by Django 5.2.17 on 2026-09-24 17:01

from django.db import migrations, models


def classify_existing_manual_cycles(apps, schema_editor):
    cycle = apps.get_model("reviews", "ReviewCycle")
    cycle.objects.using(schema_editor.connection.alias).filter(origin_kind="MANUAL").update(
        manual_purpose="INCLUSION"
    )


def unclassify_existing_manual_cycles(apps, schema_editor):
    cycle = apps.get_model("reviews", "ReviewCycle")
    if (
        cycle.objects.using(schema_editor.connection.alias)
        .filter(origin_kind="MANUAL", manual_purpose="MASTERY_REOPEN")
        .exists()
    ):
        raise RuntimeError("Mastery reopen cycles exist; use compatible-code isolated restore.")
    cycle.objects.using(schema_editor.connection.alias).filter(
        origin_kind="MANUAL", manual_purpose="INCLUSION"
    ).update(manual_purpose=None)


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("attempts", "0002_review_receipt_constraints"),
        ("questions", "0002_question_catalog"),
        ("reviews", "0004_attempt_correction_projection"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewcycle",
            name="manual_purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("INCLUSION", "Inclusão manual"),
                    ("MASTERY_REOPEN", "Reabertura de domínio"),
                ],
                max_length=24,
                null=True,
            ),
        ),
        migrations.RunPython(classify_existing_manual_cycles, unclassify_existing_manual_cycles),
        migrations.AddConstraint(
            model_name="reviewcycle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("manual_purpose__in", ["INCLUSION", "MASTERY_REOPEN"]),
                        ("origin_kind", "MANUAL"),
                    ),
                    models.Q(
                        models.Q(("origin_kind", "MANUAL"), _negated=True),
                        ("manual_purpose__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="cycle_manual_purpose_valid",
            ),
        ),
    ]
