# Generated by Django 5.2.17 on 2026-09-24 17:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


def reject_reverse_with_mastery_history(apps, schema_editor):
    event = apps.get_model("domain", "MasteryStateEvent")
    if event.objects.using(schema_editor.connection.alias).exists():
        raise RuntimeError("Mastery history exists; use compatible-code isolated restore.")


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("attempts", "0002_review_receipt_constraints"),
        ("questions", "0002_question_catalog"),
        ("reviews", "0005_reviewcycle_manual_purpose_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MasteryStateEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("DOMINATED", "Dominada"),
                            ("AUTO_REOPENED", "Reaberta automaticamente"),
                            ("MANUAL_REOPENED", "Reaberta manualmente"),
                        ],
                        max_length=24,
                    ),
                ),
                ("formula_code", models.CharField(max_length=64)),
                ("evaluated_on", models.DateField()),
                (
                    "domain_index",
                    models.DecimalField(blank=True, decimal_places=28, max_digits=36, null=True),
                ),
                (
                    "confidence",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64, null=True)),
                ("occurred_at", models.DateTimeField()),
                (
                    "manual_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="reviews.reviewcycle",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mastery_events",
                        to="questions.question",
                    ),
                ),
                (
                    "trigger_attempt",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="attempts.attempt",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="accounts.workspace"
                    ),
                ),
            ],
            options={
                "db_table": "domain_masterystateevent",
                "indexes": [
                    models.Index(
                        fields=["workspace", "question", "-sequence"], name="mastery_ws_q_seq_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("event_type__in", ["DOMINATED", "AUTO_REOPENED", "MANUAL_REOPENED"])
                        ),
                        name="mastery_event_type_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("question", "sequence"), name="mastery_q_sequence_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("sequence__gte", 1)), name="mastery_sequence_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("formula_code", ""), _negated=True),
                        name="mastery_formula_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reason_code__isnull", True),
                            models.Q(("reason_code", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="mastery_reason_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("event_type", "MANUAL_REOPENED"),
                                ("manual_cycle__isnull", False),
                                ("reason_code__isnull", False),
                            ),
                            models.Q(
                                models.Q(("event_type", "MANUAL_REOPENED"), _negated=True),
                                ("manual_cycle__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="mastery_manual_metadata_valid",
                    ),
                ],
            },
        ),
        migrations.RunPython(migrations.RunPython.noop, reject_reverse_with_mastery_history),
    ]
