# Generated by Django 5.2.17 on 2026-09-24 01:31

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SavedFilter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("name_key", models.CharField(max_length=160)),
                (
                    "context_code",
                    models.CharField(
                        choices=[("QUESTIONS_LIST", "Lista de questões")],
                        default="QUESTIONS_LIST",
                        max_length=32,
                    ),
                ),
                ("schema_version", models.PositiveSmallIntegerField(default=1)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_filters",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "search_savedfilter",
                "indexes": [
                    models.Index(
                        fields=["workspace", "owner_user", "context_code"],
                        name="search_saved_ws_owner_ctx_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("owner_user", "context_code", "name_key"),
                        name="search_saved_owner_ctx_name_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("name", ""), _negated=True),
                        name="search_saved_name_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("schema_version__gte", 1)),
                        name="search_saved_schema_positive",
                    ),
                ],
            },
        ),
    ]
