# Generated by Django 5.2.17 on 2026-09-03 00:51

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import modules.accounts.models
import modules.accounts.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("DISABLED", "Desabilitado")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounts_user",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["ACTIVE", "DISABLED"])),
                        name="accounts_user_status_valid",
                    )
                ],
            },
            managers=[
                ("objects", modules.accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "timezone_name",
                    models.CharField(
                        max_length=64,
                        validators=[modules.accounts.validators.validate_iana_timezone],
                    ),
                ),
                (
                    "locale",
                    models.CharField(
                        choices=[("pt-BR", "Português (Brasil)")], default="pt-BR", max_length=16
                    ),
                ),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workspaces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "accounts_workspace",
                "indexes": [models.Index(fields=["owner_user"], name="workspace_owner_idx")],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("lock_version__gte", 1)), name="workspace_lock_positive"
                    )
                ],
            },
        ),
    ]
