"""Códigos estáveis dos eventos operacionais exigidos na V0.1."""

from enum import StrEnum


class EventCode(StrEnum):
    """Catálogo técnico mínimo; não representa auditoria funcional."""

    APPLICATION_INITIALIZED = "APPLICATION_INITIALIZED"
    LOCAL_ACCESS_REJECTED = "LOCAL_ACCESS_REJECTED"
    HEALTH_CHECK_SUCCEEDED = "HEALTH_CHECK_SUCCEEDED"
    HEALTH_CHECK_FAILED = "HEALTH_CHECK_FAILED"
    BOOTSTRAP_STARTED = "BOOTSTRAP_STARTED"
    BOOTSTRAP_SUCCEEDED = "BOOTSTRAP_SUCCEEDED"
    BOOTSTRAP_FAILED = "BOOTSTRAP_FAILED"
    CATEGORY_SEED_STARTED = "CATEGORY_SEED_STARTED"
    CATEGORY_SEED_SUCCEEDED = "CATEGORY_SEED_SUCCEEDED"
    CATEGORY_SEED_FAILED = "CATEGORY_SEED_FAILED"
    MIGRATION_STARTED = "MIGRATION_STARTED"
    MIGRATION_SUCCEEDED = "MIGRATION_SUCCEEDED"
    MIGRATION_FAILED = "MIGRATION_FAILED"
    TIMEZONE_CHANGE_SUCCEEDED = "TIMEZONE_CHANGE_SUCCEEDED"
    TIMEZONE_CHANGE_CANCELLED = "TIMEZONE_CHANGE_CANCELLED"
    TIMEZONE_CHANGE_CONFLICT = "TIMEZONE_CHANGE_CONFLICT"
    TIMEZONE_CHANGE_FAILED = "TIMEZONE_CHANGE_FAILED"
    BACKUP_STARTED = "BACKUP_STARTED"
    BACKUP_SUCCEEDED = "BACKUP_SUCCEEDED"
    BACKUP_FAILED = "BACKUP_FAILED"
    BACKUP_VALIDATION_STARTED = "BACKUP_VALIDATION_STARTED"
    BACKUP_VALIDATION_SUCCEEDED = "BACKUP_VALIDATION_SUCCEEDED"
    BACKUP_VALIDATION_FAILED = "BACKUP_VALIDATION_FAILED"
    RESTORE_STARTED = "RESTORE_STARTED"
    RESTORE_VALIDATED = "RESTORE_VALIDATED"
    RESTORE_FAILED = "RESTORE_FAILED"


class EventOutcome(StrEnum):
    """Resultados uniformes dos eventos técnicos."""

    STARTED = "started"
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    REJECTED = "rejected"
    CANCELLED = "cancelled"
