# Generated by Django 5.2.17 on 2026-09-03 01:19

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("CONCEPTUAL", "Conceitual"),
                            ("INTERPRETATION", "Interpretação"),
                            ("CALCULATION", "Cálculo"),
                            ("ATTENTION", "Atenção"),
                            ("FORMULA_RULE", "Fórmula/regra"),
                            ("PROCEDURE", "Procedimento"),
                            ("TRAP", "Pegadinha"),
                            ("TIME_SHORTAGE", "Falta de tempo"),
                            ("GUESS", "Chute"),
                            ("OTHER", "Outra"),
                        ],
                        max_length=64,
                    ),
                ),
                ("display_name", models.CharField(max_length=120)),
                ("name_key", models.CharField(max_length=120)),
                ("description", models.CharField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="error_categories",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "errors_error_category",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "code"), name="error_category_workspace_code_uq"
                    )
                ],
            },
        ),
    ]
