# Generated by Django 5.2.17 on 2026-09-08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    run_before = [("reviews", "0001_learning_foundation")]

    dependencies = [
        ("attempts", "0001_learning_foundation"),
        ("errors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorClassification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("other_description", models.CharField(blank=True, max_length=500, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "attempt",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="error_classification",
                        to="attempts.attempt",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classifications",
                        to="errors.errorcategory",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="error_classifications",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "errors_errorclassification",
                "indexes": [
                    models.Index(
                        fields=["workspace", "category", "updated_at"],
                        name="err_class_ws_cat_upd_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("lock_version__gte", 1)),
                        name="err_class_lock_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("other_description__isnull", True),
                            models.Q(("other_description", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="err_class_other_not_empty",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ErrorClassificationRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("revision_number", models.PositiveIntegerField()),
                ("other_description", models.CharField(blank=True, max_length=500, null=True)),
                ("change_reason", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classification_revisions",
                        to="errors.errorcategory",
                    ),
                ),
                (
                    "error_classification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="errors.errorclassification",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="error_classification_revisions",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "errors_errorclassificationrevision",
                "indexes": [
                    models.Index(
                        fields=["workspace", "category", "created_at"],
                        name="err_rev_ws_cat_time_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("error_classification", "revision_number"),
                        name="err_class_revision_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision_number__gte", 1)),
                        name="err_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("other_description__isnull", True),
                            models.Q(("other_description", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="err_revision_other_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("change_reason__isnull", True),
                            models.Q(("change_reason", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="err_revision_reason_not_empty",
                    ),
                ],
            },
        ),
    ]
