"""S2A personal-category lifecycle without rewriting historical foreign keys.

Purpose: classify V0.4.4 categories as STANDARD/ACTIVE and add the nullable
merge target plus optimistic version. Defaults are semantic for every existing
standard category; there is no cosmetic or classification backfill. The code
field is widened from the form-level standard choices, and description accepts
blank personal metadata. Constraints enforce kind/state/local lifecycle,
personal normalized-name uniqueness and no direct self merge. Reversal is
technically safe before personal categories exist; after use it loses category
lifecycle and requires restore from the pre-upgrade backup. Risk: high because
current analytics depends on the canonical merge projection.
"""

# Generated by Django 5.2.17 on 2026-09-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("errors", "0002_learning_classification"),
    ]

    operations = [
        migrations.AddField(
            model_name="errorcategory",
            name="category_kind",
            field=models.CharField(
                choices=[("STANDARD", "Padrão"), ("PERSONAL", "Pessoal")],
                default="STANDARD",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="errorcategory",
            name="lock_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="errorcategory",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_sources",
                to="errors.errorcategory",
            ),
        ),
        migrations.AddField(
            model_name="errorcategory",
            name="state",
            field=models.CharField(
                choices=[("ACTIVE", "Ativa"), ("ARCHIVED", "Arquivada"), ("MERGED", "Consolidada")],
                default="ACTIVE",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="errorcategory",
            name="code",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="errorcategory",
            name="description",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddConstraint(
            model_name="errorcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("category_kind", "PERSONAL")),
                fields=("workspace", "name_key"),
                name="error_personal_ws_name_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="errorcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("category_kind__in", ["STANDARD", "PERSONAL"])),
                name="error_category_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="errorcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("category_kind", "STANDARD"),
                        (
                            "code__in",
                            [
                                "CONCEPTUAL",
                                "INTERPRETATION",
                                "CALCULATION",
                                "ATTENTION",
                                "FORMULA_RULE",
                                "PROCEDURE",
                                "TRAP",
                                "TIME_SHORTAGE",
                                "GUESS",
                                "OTHER",
                            ],
                        ),
                    ),
                    models.Q(
                        ("category_kind", "PERSONAL"),
                        ("code__startswith", "PERSONAL_"),
                    ),
                    _connector="OR",
                ),
                name="error_category_code_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="errorcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("state__in", ["ACTIVE", "ARCHIVED", "MERGED"])),
                name="error_category_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="errorcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)), name="error_category_lock_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="errorcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("category_kind", "STANDARD"),
                        ("merged_into__isnull", True),
                        ("state", "ACTIVE"),
                    ),
                    models.Q(
                        ("category_kind", "PERSONAL"),
                        ("merged_into__isnull", True),
                        ("state__in", ["ACTIVE", "ARCHIVED"]),
                    ),
                    models.Q(
                        ("category_kind", "PERSONAL"),
                        ("merged_into__isnull", False),
                        ("state", "MERGED"),
                    ),
                    _connector="OR",
                ),
                name="error_category_lifecycle_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="errorcategory",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("merged_into__isnull", True),
                    models.Q(("id", models.F("merged_into_id")), _negated=True),
                    _connector="OR",
                ),
                name="error_category_not_self_merged",
            ),
        ),
    ]
