# Generated by Django 5.2.17 on 2026-09-05 04:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discipline",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_key", models.CharField(editable=False, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("ARCHIVED", "Arquivado")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="disciplines",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={"db_table": "taxonomy_discipline"},
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_key", models.CharField(editable=False, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("ARCHIVED", "Arquivado")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discipline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="taxonomy.discipline",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subjects",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={"db_table": "taxonomy_subject"},
        ),
        migrations.CreateModel(
            name="Subsubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_key", models.CharField(editable=False, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("ARCHIVED", "Arquivado")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("sort_order", models.IntegerField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subsubjects",
                        to="taxonomy.subject",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subsubjects",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={"db_table": "taxonomy_subsubject"},
        ),
        migrations.AddIndex(
            model_name="discipline",
            index=models.Index(fields=["workspace", "status"], name="tax_disc_ws_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="discipline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("workspace", "name_key"),
                name="tax_disc_active_name_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="discipline",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "ARCHIVED"])),
                name="tax_disc_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="discipline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("archived_at__isnull", False), ("status", "ARCHIVED")),
                    _connector="OR",
                ),
                name="tax_disc_archive_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="discipline",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)),
                name="tax_disc_lock_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="subject",
            index=models.Index(
                fields=["workspace", "discipline", "status"],
                name="tax_subj_ws_disc_st_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("workspace", "discipline", "name_key"),
                name="tax_subj_active_name_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "ARCHIVED"])),
                name="tax_subj_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("archived_at__isnull", False), ("status", "ARCHIVED")),
                    _connector="OR",
                ),
                name="tax_subj_archive_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)),
                name="tax_subj_lock_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="subsubject",
            index=models.Index(
                fields=["workspace", "subject", "status"],
                name="tax_ssubj_ws_subj_st_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsubject",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("workspace", "subject", "name_key"),
                name="tax_ssubj_active_name_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsubject",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "ARCHIVED"])),
                name="tax_ssubj_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsubject",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("archived_at__isnull", False), ("status", "ARCHIVED")),
                    _connector="OR",
                ),
                name="tax_ssubj_archive_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="subsubject",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)),
                name="tax_ssubj_lock_positive",
            ),
        ),
    ]
