# Generated by Django 5.2.17 on 2026-09-08

import uuid

import django.db.models.deletion
from django.db import migrations, models

import modules.accounts.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("questions", "0002_question_catalog"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attempt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "attempt_type",
                    models.CharField(
                        choices=[("INITIAL", "Inicial"), ("REVIEW", "Revisão")],
                        max_length=16,
                    ),
                ),
                ("is_correct", models.BooleanField()),
                (
                    "perceived_ease",
                    models.CharField(
                        blank=True,
                        choices=[("EASY", "Fácil"), ("MEDIUM", "Média"), ("HARD", "Difícil")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("occurred_at", models.DateTimeField()),
                (
                    "timezone_name",
                    models.CharField(
                        max_length=64,
                        validators=[modules.accounts.validators.validate_iana_timezone],
                    ),
                ),
                ("local_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("VALID", "Válida"), ("VOIDED", "Anulada")],
                        default="VALID",
                        max_length=16,
                    ),
                ),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("void_reason", models.CharField(blank=True, max_length=1000, null=True)),
                ("idempotency_key", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="questions.question",
                    ),
                ),
                (
                    "question_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="questions.questionrevision",
                    ),
                ),
                (
                    "replaces_attempt",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="replacement_attempt",
                        to="attempts.attempt",
                    ),
                ),
                (
                    "selected_alternative",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="selected_in_attempts",
                        to="questions.alternative",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="attempts",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={"db_table": "attempts_attempt"},
        ),
    ]
