# Generated by Django 5.2.17 on 2026-09-08

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("attempts", "0001_learning_foundation"),
        ("errors", "0002_learning_classification"),
        ("reviews", "0001_learning_foundation"),
    ]

    operations = [
        migrations.AddField(
            model_name="attempt",
            name="review",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="reviews.review",
            ),
        ),
        migrations.CreateModel(
            name="OperationReceipt",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "operation_kind",
                    models.CharField(
                        choices=[
                            ("INITIAL_CORRECT", "Inicial correta"),
                            ("INITIAL_ERROR", "Erro inicial"),
                            ("REVIEW_COMPLETION", "Conclusão de revisão"),
                        ],
                        max_length=32,
                    ),
                ),
                ("idempotency_key", models.UUIDField()),
                ("request_hash", models.CharField(max_length=64)),
                (
                    "result_entity_type",
                    models.CharField(choices=[("ATTEMPT", "Tentativa")], max_length=32),
                ),
                ("result_entity_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="operation_receipts",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "attempts_operationreceipt",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("workspace", "operation_kind", "idempotency_key"),
                        name="receipt_ws_kind_key_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "operation_kind__in",
                                ["INITIAL_CORRECT", "INITIAL_ERROR", "REVIEW_COMPLETION"],
                            )
                        ),
                        name="receipt_kind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("result_entity_type__in", ["ATTEMPT"])),
                        name="receipt_result_type_valid",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["workspace", "question", "occurred_at"],
                name="attempt_ws_q_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["workspace", "status", "is_correct", "local_date"],
                name="attempt_ws_st_res_date_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="attempt",
            index=models.Index(
                fields=["workspace", "attempt_type", "local_date"],
                name="attempt_ws_type_date_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt_type", "INITIAL"), ("status", "VALID")),
                fields=("question",),
                name="attempt_initial_valid_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("review__isnull", False), ("status", "VALID")),
                fields=("review",),
                name="attempt_review_valid_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.UniqueConstraint(
                fields=("workspace", "idempotency_key"),
                name="attempt_ws_idempotency_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_type__in", ["INITIAL", "REVIEW"])),
                name="attempt_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["VALID", "VOIDED"])),
                name="attempt_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("perceived_ease__isnull", True))
                | models.Q(("perceived_ease__in", ["EASY", "MEDIUM", "HARD"])),
                name="attempt_ease_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("attempt_type", "INITIAL"), ("review__isnull", True))
                | models.Q(("attempt_type", "REVIEW"), ("review__isnull", False)),
                name="attempt_type_review_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status", "VALID"),
                    ("void_reason__isnull", True),
                    ("voided_at__isnull", True),
                )
                | models.Q(
                    ("status", "VOIDED"),
                    ("void_reason__isnull", False),
                    ("voided_at__isnull", False),
                ),
                name="attempt_void_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="attempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("void_reason__isnull", True)) | ~models.Q(("void_reason", "")),
                name="attempt_void_reason_valid",
            ),
        ),
    ]
