"""S2A audit foundation.

Purpose: add the closed, append-only functional event table. V0.4.4 remains
compatible because no existing table or row changes and no backfill is run.
All event metadata is required or nullable exactly as modeled; constraints
close event/entity values and reschedule metadata. Reversal is safe before S2A
events exist; after functional use it would discard audit history, so restore
from the pre-upgrade backup is recommended. Risk: high because audit loss is
not an acceptable operational rollback.
"""

# Generated by Django 5.2.17 on 2026-09-20 15:05

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "event_code",
                    models.CharField(
                        choices=[
                            ("REVIEW_RESCHEDULED", "Review reagendada"),
                            ("MANUAL_REVIEW_INCLUDED", "Review incluída manualmente"),
                            ("PERSONAL_CATEGORY_RENAMED", "Categoria pessoal renomeada"),
                            ("PERSONAL_CATEGORY_ARCHIVED", "Categoria pessoal arquivada"),
                            ("PERSONAL_CATEGORY_MERGED", "Categoria pessoal consolidada"),
                        ],
                        max_length=40,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("REVIEW", "Review"),
                            ("REVIEW_CYCLE", "Ciclo de revisão"),
                            ("ERROR_CATEGORY", "Categoria de erro"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_id", models.UUIDField()),
                ("related_entity_id", models.UUIDField(blank=True, null=True)),
                ("correlation_id", models.UUIDField()),
                ("reason_code", models.CharField(blank=True, max_length=64, null=True)),
                ("previous_date", models.DateField(blank=True, null=True)),
                ("new_date", models.DateField(blank=True, null=True)),
                ("timezone_name", models.CharField(blank=True, max_length=64, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="audit_events",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "operations_auditevent",
                "indexes": [
                    models.Index(
                        fields=["workspace", "event_code", "created_at"],
                        name="audit_ws_code_time_idx",
                    ),
                    models.Index(
                        fields=["workspace", "entity_type", "entity_id"], name="audit_ws_entity_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "event_code__in",
                                [
                                    "REVIEW_RESCHEDULED",
                                    "MANUAL_REVIEW_INCLUDED",
                                    "PERSONAL_CATEGORY_RENAMED",
                                    "PERSONAL_CATEGORY_ARCHIVED",
                                    "PERSONAL_CATEGORY_MERGED",
                                ],
                            )
                        ),
                        name="audit_event_code_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("entity_type__in", ["REVIEW", "REVIEW_CYCLE", "ERROR_CATEGORY"])
                        ),
                        name="audit_entity_type_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("reason_code__isnull", True),
                            models.Q(("reason_code", ""), _negated=True),
                            _connector="OR",
                        ),
                        name="audit_reason_not_empty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("entity_type", "REVIEW"),
                                ("event_code", "REVIEW_RESCHEDULED"),
                                ("new_date__isnull", False),
                                ("previous_date__isnull", False),
                                ("reason_code__isnull", False),
                                ("timezone_name__isnull", False),
                            ),
                            models.Q(("event_code", "REVIEW_RESCHEDULED"), _negated=True),
                            _connector="OR",
                        ),
                        name="audit_reschedule_metadata_valid",
                    ),
                ],
            },
        ),
    ]
