# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("operations", "0001_initial")]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_event_code_valid",
        ),
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_entity_type_valid",
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("REVIEW", "Review"),
                    ("REVIEW_CYCLE", "Ciclo de revisão"),
                    ("ERROR_CATEGORY", "Categoria de erro"),
                    ("ATTEMPT", "Tentativa"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_code",
            field=models.CharField(
                choices=[
                    ("REVIEW_RESCHEDULED", "Review reagendada"),
                    ("MANUAL_REVIEW_INCLUDED", "Review incluída manualmente"),
                    ("PERSONAL_CATEGORY_RENAMED", "Categoria pessoal renomeada"),
                    ("PERSONAL_CATEGORY_ARCHIVED", "Categoria pessoal arquivada"),
                    ("PERSONAL_CATEGORY_MERGED", "Categoria pessoal consolidada"),
                    ("ATTEMPT_VOIDED", "Tentativa anulada"),
                    ("ATTEMPT_REPLACED", "Tentativa substituída"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    event_code__in=[
                        "REVIEW_RESCHEDULED",
                        "MANUAL_REVIEW_INCLUDED",
                        "PERSONAL_CATEGORY_RENAMED",
                        "PERSONAL_CATEGORY_ARCHIVED",
                        "PERSONAL_CATEGORY_MERGED",
                        "ATTEMPT_VOIDED",
                        "ATTEMPT_REPLACED",
                    ]
                ),
                name="audit_event_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    entity_type__in=[
                        "REVIEW",
                        "REVIEW_CYCLE",
                        "ERROR_CATEGORY",
                        "ATTEMPT",
                    ]
                ),
                name="audit_entity_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        event_code__in=("ATTEMPT_VOIDED", "ATTEMPT_REPLACED"),
                        entity_type="ATTEMPT",
                        reason_code__isnull=False,
                        previous_date__isnull=True,
                        new_date__isnull=True,
                        timezone_name__isnull=True,
                    )
                    | ~models.Q(event_code__in=("ATTEMPT_VOIDED", "ATTEMPT_REPLACED"))
                ),
                name="audit_attempt_metadata_valid",
            ),
        ),
    ]
