"""S2C answer-key correction audit metadata.

Purpose: admit the closed ANSWER_KEY_CORRECTED event and retain Question,
previous revision and new revision technical IDs without content. The nullable
column is additive, has no default and receives no backfill; S2A/S2B rows stay
unchanged. Reverse is safe before S2C facts exist. After real corrections,
restore with compatible code is required because reverse would discard
mandatory audit history. Risk: high because silent audit loss is unacceptable.
"""

# Generated by Django 5.2.17 on 2026-09-20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("operations", "0002_attempt_audit_events")]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_event_code_valid",
        ),
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_entity_type_valid",
        ),
        migrations.AddField(
            model_name="auditevent",
            name="previous_entity_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="entity_type",
            field=models.CharField(
                choices=[
                    ("REVIEW", "Review"),
                    ("REVIEW_CYCLE", "Ciclo de revisão"),
                    ("ERROR_CATEGORY", "Categoria de erro"),
                    ("ATTEMPT", "Tentativa"),
                    ("QUESTION", "Questão"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_code",
            field=models.CharField(
                choices=[
                    ("REVIEW_RESCHEDULED", "Review reagendada"),
                    ("MANUAL_REVIEW_INCLUDED", "Review incluída manualmente"),
                    ("PERSONAL_CATEGORY_RENAMED", "Categoria pessoal renomeada"),
                    ("PERSONAL_CATEGORY_ARCHIVED", "Categoria pessoal arquivada"),
                    ("PERSONAL_CATEGORY_MERGED", "Categoria pessoal consolidada"),
                    ("ATTEMPT_VOIDED", "Tentativa anulada"),
                    ("ATTEMPT_REPLACED", "Tentativa substituída"),
                    ("ANSWER_KEY_CORRECTED", "Gabarito corrigido"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    event_code__in=[
                        "REVIEW_RESCHEDULED",
                        "MANUAL_REVIEW_INCLUDED",
                        "PERSONAL_CATEGORY_RENAMED",
                        "PERSONAL_CATEGORY_ARCHIVED",
                        "PERSONAL_CATEGORY_MERGED",
                        "ATTEMPT_VOIDED",
                        "ATTEMPT_REPLACED",
                        "ANSWER_KEY_CORRECTED",
                    ]
                ),
                name="audit_event_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    entity_type__in=[
                        "REVIEW",
                        "REVIEW_CYCLE",
                        "ERROR_CATEGORY",
                        "ATTEMPT",
                        "QUESTION",
                    ]
                ),
                name="audit_entity_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        event_code="ANSWER_KEY_CORRECTED",
                        entity_type="QUESTION",
                        previous_entity_id__isnull=False,
                        related_entity_id__isnull=False,
                        reason_code__isnull=False,
                        previous_date__isnull=True,
                        new_date__isnull=True,
                        timezone_name__isnull=True,
                    )
                    | (
                        ~models.Q(event_code="ANSWER_KEY_CORRECTED")
                        & models.Q(previous_entity_id__isnull=True)
                    )
                ),
                name="audit_answer_key_metadata_valid",
            ),
        ),
    ]
