"""S2D: evento de exclusão sem ID da Question e correlação única.

Migração aditiva de escolha/constraint e nulabilidade; não cria eventos nem
altera fatos existentes. Reverse só é seguro antes de eventos S2D. Após
exclusão real, recovery do conteúdo requer backup compatível pré-delete.
"""

# Generated by Django 5.2.17 on 2026-09-23 15:13

from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("operations", "0003_answer_key_correction_audit"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="auditevent",
            name="audit_event_code_valid",
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="entity_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="auditevent",
            name="event_code",
            field=models.CharField(
                choices=[
                    ("REVIEW_RESCHEDULED", "Review reagendada"),
                    ("MANUAL_REVIEW_INCLUDED", "Review incluída manualmente"),
                    ("PERSONAL_CATEGORY_RENAMED", "Categoria pessoal renomeada"),
                    ("PERSONAL_CATEGORY_ARCHIVED", "Categoria pessoal arquivada"),
                    ("PERSONAL_CATEGORY_MERGED", "Categoria pessoal consolidada"),
                    ("ATTEMPT_VOIDED", "Tentativa anulada"),
                    ("ATTEMPT_REPLACED", "Tentativa substituída"),
                    ("ANSWER_KEY_CORRECTED", "Gabarito corrigido"),
                    ("QUESTION_PERMANENTLY_DELETED", "Questão excluída permanentemente"),
                ],
                max_length=40,
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "event_code__in",
                        [
                            "REVIEW_RESCHEDULED",
                            "MANUAL_REVIEW_INCLUDED",
                            "PERSONAL_CATEGORY_RENAMED",
                            "PERSONAL_CATEGORY_ARCHIVED",
                            "PERSONAL_CATEGORY_MERGED",
                            "ATTEMPT_VOIDED",
                            "ATTEMPT_REPLACED",
                            "ANSWER_KEY_CORRECTED",
                            "QUESTION_PERMANENTLY_DELETED",
                        ],
                    )
                ),
                name="audit_event_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("entity_id__isnull", True),
                        ("entity_type", "QUESTION"),
                        ("event_code", "QUESTION_PERMANENTLY_DELETED"),
                        ("new_date__isnull", True),
                        ("previous_date__isnull", True),
                        ("previous_entity_id__isnull", True),
                        ("reason_code__isnull", False),
                        ("related_entity_id__isnull", True),
                        ("timezone_name__isnull", True),
                    ),
                    models.Q(
                        models.Q(("event_code", "QUESTION_PERMANENTLY_DELETED"), _negated=True),
                        ("entity_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="audit_delete_metadata_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="auditevent",
            constraint=models.UniqueConstraint(
                fields=["workspace", "event_code", "correlation_id"],
                condition=Q(event_code="QUESTION_PERMANENTLY_DELETED"),
                name="audit_delete_correlation_uq",
            ),
        ),
    ]
