# Generated by Django 5.2.17 on 2026-09-06 03:01

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_key", models.CharField(editable=False, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("ARCHIVED", "Arquivado")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("website_url", models.URLField(blank=True, max_length=2048, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="boards",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "questions_board",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_key", models.CharField(editable=False, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("ARCHIVED", "Arquivado")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.SmallIntegerField(blank=True, null=True)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="questions.board",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exams",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "questions_exam",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("name_key", models.CharField(editable=False, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Ativo"), ("ARCHIVED", "Arquivado")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("BOOK", "Livro"),
                            ("PDF", "PDF"),
                            ("WEBSITE", "Site"),
                            ("COURSE", "Curso"),
                            ("QUESTION_BANK", "Banco de questões"),
                            ("OTHER", "Outra"),
                        ],
                        max_length=24,
                    ),
                ),
                ("locator_url", models.URLField(blank=True, max_length=2048, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sources",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "questions_source",
            },
        ),
        migrations.AddIndex(
            model_name="board",
            index=models.Index(
                fields=["workspace", "status", "name_key"], name="q_board_ws_st_name_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("workspace", "name_key"),
                name="q_board_active_name_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "ARCHIVED"])),
                name="q_board_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("archived_at__isnull", False), ("status", "ARCHIVED")),
                    _connector="OR",
                ),
                name="q_board_archive_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="board",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)), name="q_board_lock_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="exam",
            index=models.Index(
                fields=["workspace", "board", "year"], name="q_exam_ws_board_year_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("board__isnull", True), ("status", "ACTIVE"), ("year__isnull", True)
                ),
                fields=("workspace", "name_key"),
                name="q_exam_active_none_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("board__isnull", True), ("status", "ACTIVE"), ("year__isnull", False)
                ),
                fields=("workspace", "name_key", "year"),
                name="q_exam_active_year_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("board__isnull", False), ("status", "ACTIVE"), ("year__isnull", True)
                ),
                fields=("workspace", "board", "name_key"),
                name="q_exam_active_board_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("board__isnull", False), ("status", "ACTIVE"), ("year__isnull", False)
                ),
                fields=("workspace", "board", "name_key", "year"),
                name="q_exam_active_full_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "ARCHIVED"])),
                name="q_exam_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("archived_at__isnull", False), ("status", "ARCHIVED")),
                    _connector="OR",
                ),
                name="q_exam_archive_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)), name="q_exam_lock_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="exam",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__isnull", True), ("year__gte", 1900), _connector="OR"),
                name="q_exam_year_minimum",
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(
                fields=["workspace", "source_type", "status"], name="q_source_ws_type_st_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="source",
            index=models.Index(fields=["workspace", "name_key"], name="q_source_ws_name_idx"),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "ACTIVE")),
                fields=("workspace", "source_type", "name_key"),
                name="q_source_active_name_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "source_type__in",
                        ["BOOK", "PDF", "WEBSITE", "COURSE", "QUESTION_BANK", "OTHER"],
                    )
                ),
                name="q_source_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["ACTIVE", "ARCHIVED"])),
                name="q_source_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("archived_at__isnull", True), ("status", "ACTIVE")),
                    models.Q(("archived_at__isnull", False), ("status", "ARCHIVED")),
                    _connector="OR",
                ),
                name="q_source_archive_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="source",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)), name="q_source_lock_positive"
            ),
        ),
    ]
