# Generated by Django 5.2.17 on 2026-09-06 16:00

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_origin_catalog"),
        ("taxonomy", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[("OBJECTIVE_SINGLE", "Objetiva de resposta única")],
                        default="OBJECTIVE_SINGLE",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("ACTIVE", "Ativa"),
                            ("ARCHIVED", "Arquivada"),
                        ],
                        default="DRAFT",
                        max_length=16,
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        blank=True,
                        choices=[("EASY", "Fácil"), ("MEDIUM", "Média"), ("HARD", "Difícil")],
                        max_length=16,
                        null=True,
                    ),
                ),
                ("draft_title", models.CharField(blank=True, max_length=200, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("archived_at", models.DateTimeField(blank=True, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discipline",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="taxonomy.discipline",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="taxonomy.subject",
                    ),
                ),
                (
                    "subsubject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="taxonomy.subsubject",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="questions",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "questions_question",
            },
        ),
        migrations.CreateModel(
            name="QuestionOrigin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reference_year", models.SmallIntegerField(blank=True, null=True)),
                ("reference_text", models.CharField(blank=True, max_length=1000, null=True)),
                ("lock_version", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_origins",
                        to="questions.board",
                    ),
                ),
                (
                    "exam",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_origins",
                        to="questions.exam",
                    ),
                ),
                (
                    "question",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="origin",
                        to="questions.question",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_origins",
                        to="questions.source",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_origins",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "questions_questionorigin",
            },
        ),
        migrations.CreateModel(
            name="QuestionRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("is_current", models.BooleanField(default=False)),
                ("stem", models.TextField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("trap_note", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "change_kind",
                    models.CharField(
                        choices=[
                            ("INITIAL", "Inicial"),
                            ("ENRICHMENT", "Enriquecimento"),
                            ("NON_CRITICAL_EDIT", "Edição não crítica"),
                            ("CRITICAL_CORRECTION", "Correção crítica"),
                        ],
                        max_length=24,
                    ),
                ),
                ("change_reason", models.CharField(blank=True, max_length=1000, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="revisions",
                        to="questions.question",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_revisions",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "questions_questionrevision",
            },
        ),
        migrations.CreateModel(
            name="Alternative",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                ("label", models.CharField(blank=True, max_length=10, null=True)),
                ("text", models.TextField()),
                ("text_key", models.TextField(editable=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "question_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="alternatives",
                        to="questions.questionrevision",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="question_alternatives",
                        to="accounts.workspace",
                    ),
                ),
            ],
            options={
                "db_table": "questions_alternative",
            },
        ),
        migrations.AddField(
            model_name="questionrevision",
            name="correct_alternative",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="correct_for_revisions",
                to="questions.alternative",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["workspace", "status", "updated_at"], name="q_question_ws_st_upd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["workspace", "discipline", "subject", "subsubject", "status"],
                name="q_question_tax_st_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="question",
            index=models.Index(
                fields=["workspace", "difficulty", "status"], name="q_question_diff_st_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("question_type__in", ["OBJECTIVE_SINGLE"])),
                name="q_question_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["DRAFT", "ACTIVE", "ARCHIVED"])),
                name="q_question_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("difficulty__isnull", True),
                    ("difficulty__in", ["EASY", "MEDIUM", "HARD"]),
                    _connector="OR",
                ),
                name="q_question_difficulty_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)), name="q_question_lock_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discipline__isnull", False), ("subject__isnull", True), _connector="OR"
                ),
                name="q_question_subject_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("subject__isnull", False), ("subsubject__isnull", True), _connector="OR"
                ),
                name="q_question_subsubject_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "ACTIVE"), _negated=True),
                    models.Q(("discipline__isnull", False), ("subject__isnull", False)),
                    _connector="OR",
                ),
                name="q_question_active_taxonomy",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activated_at__isnull", True),
                        ("archived_at__isnull", True),
                        ("status", "DRAFT"),
                    ),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("archived_at__isnull", True),
                        ("status", "ACTIVE"),
                    ),
                    models.Q(("archived_at__isnull", False), ("status", "ARCHIVED")),
                    _connector="OR",
                ),
                name="q_question_state_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("draft_title__isnull", True),
                    models.Q(("draft_title", ""), _negated=True),
                    _connector="OR",
                ),
                name="q_question_title_not_empty",
            ),
        ),
        migrations.AddIndex(
            model_name="questionorigin",
            index=models.Index(fields=["workspace", "source"], name="q_origin_ws_source_idx"),
        ),
        migrations.AddIndex(
            model_name="questionorigin",
            index=models.Index(fields=["workspace", "exam"], name="q_origin_ws_exam_idx"),
        ),
        migrations.AddIndex(
            model_name="questionorigin",
            index=models.Index(fields=["workspace", "board"], name="q_origin_ws_board_idx"),
        ),
        migrations.AddConstraint(
            model_name="questionorigin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exam__isnull", True), ("board__isnull", True), _connector="OR"
                ),
                name="q_origin_exam_board_exclusive",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionorigin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exam__isnull", True), ("reference_year__isnull", True), _connector="OR"
                ),
                name="q_origin_exam_year_derived",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionorigin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reference_year__isnull", True), ("reference_year__gte", 1900), _connector="OR"
                ),
                name="q_origin_year_minimum",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionorigin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source__isnull", False),
                    ("exam__isnull", False),
                    ("board__isnull", False),
                    ("reference_year__isnull", False),
                    models.Q(
                        ("reference_text__isnull", False),
                        models.Q(("reference_text", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="q_origin_has_data",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionorigin",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("reference_text__isnull", True),
                    models.Q(("reference_text", ""), _negated=True),
                    _connector="OR",
                ),
                name="q_origin_reference_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionorigin",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_version__gte", 1)), name="q_origin_lock_positive"
            ),
        ),
        migrations.AddIndex(
            model_name="questionrevision",
            index=models.Index(
                fields=["workspace", "question", "created_at"], name="q_revision_ws_q_cr_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrevision",
            constraint=models.UniqueConstraint(
                fields=("question", "version_number"), name="q_revision_version_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("question",),
                name="q_revision_current_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("version_number__gte", 1)), name="q_revision_version_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "change_kind__in",
                        ["INITIAL", "ENRICHMENT", "NON_CRITICAL_EDIT", "CRITICAL_CORRECTION"],
                    )
                ),
                name="q_revision_change_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("change_kind", "CRITICAL_CORRECTION"), _negated=True),
                    models.Q(
                        ("change_reason__isnull", False),
                        models.Q(("change_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="q_revision_critical_reason",
            ),
        ),
        migrations.AddConstraint(
            model_name="questionrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stem__isnull", True), models.Q(("stem", ""), _negated=True), _connector="OR"
                ),
                name="q_revision_stem_not_empty",
            ),
        ),
        migrations.AddConstraint(
            model_name="alternative",
            constraint=models.UniqueConstraint(
                fields=("question_revision", "position"), name="q_alternative_position_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="alternative",
            constraint=models.UniqueConstraint(
                fields=("question_revision", "text_key"), name="q_alternative_text_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="alternative",
            constraint=models.CheckConstraint(
                condition=models.Q(("position__gte", 1)), name="q_alternative_position_positive"
            ),
        ),
        migrations.AddConstraint(
            model_name="alternative",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("text", ""), _negated=True), models.Q(("text_key", ""), _negated=True)
                ),
                name="q_alternative_text_not_empty",
            ),
        ),
    ]
